ENT.Type = "anim"
ENT.Base = "base_anim"
ENT.PrintName = "Rotating alert light"
ENT.Author = "MetaMan"
ENT.Information = "A rotating, red alert light."
ENT.RenderGroup = RENDERGROUP_OPAQUE
ENT.Spawnable = false
ENT.AdminSpawnable = false
ENT.PhysgunDisabled = true
ENT.m_tblToolsAllowed = {}
